FROM nginx:alpine

WORKDIR /usr/src/app/

# 创建 SSL 证书目录
RUN mkdir -p /etc/nginx/ssl

# 复制 Nginx 配置
COPY ./docker/nginx.conf /etc/nginx/conf.d/default.conf

# 复制 SSL 证书
COPY ./ssl/_.tagtjn.cn.crt /etc/nginx/ssl/
COPY ./ssl/_.tagtjn.cn.key /etc/nginx/ssl/

# 复制前端文件
COPY ./dist  /usr/share/nginx/html/

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]